name: Build Showcase

on:
  push:
    branches:
      - "master"
    paths:
      - "apps/showcase/**"
  pull_request:
    branches:
      - "*"
    paths:
      - "apps/showcase/**"

env:
  PROJECT_PATH: "apps/showcase"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup Node"
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v2
        with:
          version: "8"

      - name: "Install packages"
        run: "pnpm install"
        working-directory: ${{ env.PROJECT_PATH }}

      - name: "Lint"
        run: "pnpm lint"
        working-directory: ${{ env.PROJECT_PATH }}

      - name: "Test"
        run: "pnpm test:ci"
        working-directory: ${{ env.PROJECT_PATH }}

      - name: "Build"
        run: "pnpm build"
        working-directory: ${{ env.PROJECT_PATH }}
